spring:
    application:
        name: Loyalty Management Standalone Application
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/lmsabackend
        username: root
        password: password
    jpa:
        show-sql: false
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
                implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        properties:
            hibernate:
                format_sql: true
            dialect: org.hibernate.dialect.MySQL8Dialect
    mail:
        host: smtp.gmail.com
        port: 587
        username: ratnenddr.girri@gmail.com
        password: safas
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
                        required: true
                    ssl:
                        trust: smtp.gmail.com

server:
    port: 8080
    servlet:
        context-path: /lmsa

jwt:
    secret: my_super_secret_key_is_very_secret_JWT_key_123456789

source:
    file:
        path: D:/RewardHistory/SRTFILE.xlsx

